# Generated by Django 5.1.5 on 2025-01-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
