# Generated by Django 5.1.5 on 2025-01-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_blog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="default_image.jpg",
                upload_to="blog_images/",
                verbose_name="Imagen",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="subtitle",
            field=models.CharField(
                default="default_image.jpg", max_length=300, verbose_name="Subtítulo"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="Cuerpo"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
    ]
