# Generated by Django 5.1.5 on 2025-02-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_alter_message_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
